on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: install adk
        shell: cmd
        run: |
          curl -LO "https://go.microsoft.com/fwlink/?linkid=2289980"
          start /wait adksetup.exe /q /norestart /ceip off /features OptionId.DeploymentTools
